version: 1.0.{build}
skip_branch_with_pr: true
image: Visual Studio 2015
install:
  - cmd: appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/v3.5.0/NuGet.exe
before_build:
  - nuget restore couchbase-aspnet-core.sln
build:
  verbosity: minimal
test:
  assemblies:
    - '**\Couchbase.Extensions.Caching.UnitTests.dll'
